#!/bin/bash -v

# gmsh installation just seems to be messed up. It works
# if we install via gmsh and then uninstall / reinstall via pip

mamba env list
mamba init
mamba activate notebook

mamba uninstall gmsh --no-prune-deps
pip install gmsh

# Build / install the uw2 + uw3 in this repo


git clone --single-branch --branch development https://github.com/underworldcode/underworld3.git
cd underworld3
./compile.sh
cd ..

git clone --single-branch --branch development https://github.com/underworldcode/underworld2.git
cd underworld2
pip install . --no-build-isolation
cd ..

git clone --single-branch https://github.com/underworld-community/uw-demo-bitsnpieces.git ./uw-demo

wget https://github.com/underworldcode/underworld3-documentation/archive/refs/heads/main.zip
unzip main.zip "underworld3-documentation-main/Notebooks/Examples-Loop-Mesh/*"
mv underworld3-documentation-main/Notebooks/Examples-Loop-Mesh ./Examples-Loop-Mesh
rm -rf main.zip underworld3-documentation-main

echo
echo "Build at" > ~/.time_of_env_creation
date >> ~/.time_of_env_creation
echo
