#!/bin/bash -v


# Build / install the uw2 + uw3 in this repo


git clone --single-branch --branch development https://github.com/underworldcode/underworld3.git
cd underworld3
pip install . --no-build-isolation
cd ..

git clone --single-branch --branch development https://github.com/underworldcode/underworld2.git
cd underworld2
pip install . --no-build-isolation
cd ..

git clone --single-branch https://github.com/underworld-community/uw-demo-bitsnpieces.git ./uw-demo

echo
echo "Build at" > ~/.time_of_creation
date >> ~/.time_of_creation
echo
