#!/bin/bash -v

# gmsh installation just seems to be messed up. It works
# if we install via gmsh and then uninstall / reinstall via pip

mamba env list
mamba init
mamba activate notebook

mamba uninstall gmsh --no-prune-deps
pip install gmsh

# Build / install underworld3 from uw3-release-candidate branch

git clone --single-branch --branch uw3-release-candidate https://github.com/underworldcode/underworld3.git
cd underworld3
pip install . --no-build-isolation
cd ..

# Copy beginner tutorials to workspace
cp -r underworld3/docs/beginner/tutorials ./Tutorials

echo
echo "Build at" > ~/.time_of_env_creation
date >> ~/.time_of_env_creation
echo
