#!/bin/bash

# Quick rebuild of latest version of uw3

cd underworld3
git stash
git pull
pip install . --no-build-isolation
cd ..

## This is not required for the conda-forge version of petsc but
## it is needed if we install the uw3_env dependencies



export PYTHONPATH=$CONDA_PREFIX/lib/ 

exec "$@"
