#!/bin/bash
set -e

export PATH="$HOME/.pixi/bin:$PATH"

# Quick rebuild of latest uw3 from uw3-release-candidate
cd underworld3
git stash
git checkout uw3-release-candidate
git pull origin uw3-release-candidate
pixi run -e runtime build
cd ..

# Update tutorials if changed
cp -r underworld3/docs/beginner/tutorials/* ./Tutorials/ 2>/dev/null || true

exec "$@"
